name: MultiplayerParkour
version: '${version}'
main: com.waste.multiplayerparkour.MultiplayerParkour
api-version: 1.16

commands:
  checkpointstick:
    description: Gives you a checkpoint stick
    usage: /checkpointstick
    permission: multiplayerparkour.checkpointstick

  removecheckpoint:
    description: Removes a checkpoint
    usage: /removecheckpoint
    permission: multiplayerparkour.removecheckpoint

  checkpointlist:
    description: Lists all checkpoints
    usage: /checkpointlist
    permission: multiplayerparkour.checkpointlist

  checkpoint:
    description: Teleports you to a checkpoint
    usage: /checkpoint
    permission: multiplayerparkour.checkpoint